### ISSUE TITLE
deathlyhallows upgrade causes inexplicable background counts tps plummets

### ISSUE THREAD

**Issue by mcmso** [PydingAbsorber/DeathlyHallows#2]
deathlyhallows-1.0.19→deathlyhallows-1.0.20-hotfix
![image](https://github.com/PydingAbsorber/DeathlyHallows/assets/46519955/8b51fa98-6678-4809-9829-6f49e606df0e)
Version is back to deathlyhallows-1.0.19
Return to normal

**Comment by PydingAbsorber** [comment]
So 1.0.19 is ok and 1.0.20 lagging?

**Comment by mcmso** [comment]
> So 1.0.19 is ok and 1.0.20 lagging?

Yes.

**Comment by PydingAbsorber** [comment]
Thank you for report! I will try to solve the problem later

**Comment by mcmso** [comment]
> Thank you for report! I will try to solve the problem later

It's like a counter
Keep adding numbers in the background
I suspect it has something to do with it.   Can you think about whether the relevant new features have anything to do with him?   I think this is a good starting point to solve the problem
Thank you very much for your maintenance of this mod

**Comment by PydingAbsorber** [comment]
So got my hands finally on this. I know what's the issue is and fix will be in hours. Also optimized some code

**Comment by PydingAbsorber** [comment]
Damage for monster book now will scale from each new type of monster killed

**Comment by PydingAbsorber** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/deathly-hallows/files/4882369
