### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by avescarelo** [PydingAbsorber/DeathlyHallows#4]
Hey!
When i push (by hand, sword etc) another player i get this chat spam :(

![image](https://github.com/PydingAbsorber/DeathlyHallows/assets/26678843/be5755d1-18d5-485f-9b25-c96fb3b815f6)

**Comment by PydingAbsorber** [comment]
Hi, that means you enabled ,,/deathlyhallows damagelog,,! Just type that command again to disable and let me know if it worked

**Comment by avescarelo** [comment]
Hey
I not enadbled this, but when i writed this command i get this:

![image](https://github.com/PydingAbsorber/DeathlyHallows/assets/26678843/c5f1be7f-a34d-4f63-bb9e-364a907630df)

**Comment by AirBurn0** [comment]
Problem was reproduced and solved by now.
New release will not contain that bug.
